version: '3.4'

services:
  one-api:
    image: "${REGISTRY:-docker.io}/justsong/one-api:latest"
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data/oneapi:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=oneapi:oNe_api!123456@tcp(db:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
      - SYNC_FREQUENCY=60 # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "${REGISTRY:-docker.io}/redis:latest"
    container_name: redis
    restart: always

  db:
    image: "${REGISTRY:-docker.io}/mysql:8.2.0"
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai   # 设置时区
      MYSQL_ROOT_PASSWORD: 'Xhi6@8?El9b%m!o~0' # 设置 root 用户的密码
      MYSQL_USER: oneapi   # 创建专用用户
      MYSQL_PASSWORD: 'oNe_api!123456'    # 设置专用用户密码
      MYSQL_DATABASE: one-api   # 自动创建数据库
  gpt4free:
    # 非星球用户请使用此镜像 xiangsx/gpt4free-ts:latest
    # 星球用户请使用此镜像 gpt4freets/gpt4free-ts:v0.0.192-private
    image: xiangsx/gpt4free-ts:latest
    container_name: gpt4free-ts
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - ./g4fts/run:/usr/src/app/run
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    environment:
      - TZ=Asia/Shanghai #设置时区
      # 启动进程数量，不建议改动
      - WORKERS=1
      # auto站点失败自动重试次数
      - AUTO_RETRY_TIMES=3
      # 日志登记 info、warn、error
      - LOG_LEVEL=info
      # 默认不配置为开启控制台日志 0-关闭 1-开启
      - LOG_CONSOLE=1
      # 是否开启文件日志
      - LOG_FILE=0
      # clash 代理地址
      #- http_proxy=http://clash:7890
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ./clash/config.yaml:/root/.config/clash/config.yaml
      - ./clash/profiles:/root/.config/clash/profiles
    ports:
      - "7890:7890"
      - "9090:9090" # external controller (Restful API)
    restart: always
    environment:
      - TZ=Asia/Shanghai # 设置时区
